### ISSUE TITLE
HIPAA/PIPEDA compliance?

### ISSUE THREAD

**Issue by adamak93** [singularitypress/vaxx-frontend#5]
Admittedly, this is a bit of a long shot given what we're building and since we're dealing with postal codes and stuff like that, would there be a need to look into HIPAA and PIPEDA compliance just to stay on the right side of the law? 

https://www.givainc.com/blog/index.cfm/2019/12/13/How-Does-HIPAA-Differ-from-PIPEDA#:~:text=In%20the%20United%20States%2C%20HIPAA%20is%20a%20federal,healthcare%20industry%20or%20elsewhere%2C%20regardless%20of%20the%20entity.

**Comment by singularitypress** [comment]
Thanks for the heads up; I just added this to the Readme
