### ISSUE TITLE
UI Mockup

### ISSUE THREAD

**Issue by adamak93** [singularitypress/vaxx-frontend#6]
I figure this would be a good place as ever to stick ideas for mockups and UI ideas/ stuff to improve UX. I'm posting a rough mockup from JMan on discord that'll give us a better idea of what to do with stuff like this. 

![image](https://user-images.githubusercontent.com/5358592/114941656-6caf6a00-9e11-11eb-92c2-b49b7febd893.png)

**Comment by singularitypress** [comment]
Thanks Adam! There's an Invision WIP at present; I'll post it in the readme when it's done.
